### ISSUE TITLE
Use command-line arguments to provide config

### ISSUE THREAD

**Issue by numaru** [nerosscadernis/RebirthCore#2]
To allow scripts to run the servers, we could use args to fill the configurations.

For the auth server we need:

 - A Mysql connection string
 - A port for the client
 - A port for the world server

For the world server we need:

 - A Mysql connection string
 - A port for the client
 - The host address/port of the auth server

I think we should not factoring these parameters because it will allow us to execute the services on different machines.

 ---

I propose these names:

- `--auth-mysql` for the auth database connection string.
- `--world-mysql` for the world database connection string.
- `--auth-port` for the auth port to the client.
- `--world-port` for the world port to the client.
- `--inter-port` for the auth port to the world server.
- `--inter-host` for the auth address to the world server.
- `--run=[all|world|auth]` to select the services to run.

All these params could be fill with default values bound to localhost and default ports.

**Comment by nerosscadernis** [comment]
Config or Args is a same. It's possible to add this function yes. :)

**Comment by numaru** [comment]
Ok, let's use config files then.
